# Stage 1
FROM node:17 as react-build
WORKDIR /app

# Install dependencies
COPY package.json .
#RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000
CMD ["npm","start"]

#
## Stage 2 - the production environment with nginx
#FROM nginx:alpine
#COPY nginx.conf /etc/nginx/conf.d/default.conf
#COPY --from=react-build /app/build /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
